class DeviceInfo {
  // ...existing code...
  final bool hasNfc;
  // ...existing code...
  
  DeviceInfo({
    // ...existing parameters...
    required this.hasNfc,
    // ...existing parameters...
  });
}
