class PaymentMethod {
  // ...existing code...
  final bool isNfcSupported;
  // ...existing code...
  
  PaymentMethod({
    // ...existing parameters...
    required this.isNfcSupported,
    // ...existing parameters...
  });
}
